# Generated by Django 6.0.6 on 2026-07-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='avtrs/default_avtr.jpg', upload_to='avtrs/'),
        ),
    ]
